library(shinydashboard)

# Define UI for application that draws a histogram
shinyUI(fluidPage(useShinyjs(),
                  dashboardPage(
                    dashboardHeader(title = 'HALO Object Analysis'),
                    
                    dashboardSidebar(width = 300,
                                     sidebarMenu(
                                       menuItem('Data', 
                                                tabName = 'file_input',
                                                fileInput('file',
                                                          label = 'File input',
                                                          multiple = F,
                                                          accept = c(".tsv",
                                                                     ".csv")),
                                                selectInput('file_select',
                                                            label = 'Select file',
                                                            choices = c('example.csv')),
                                                actionButton('update_file',
                                                             'Parse Data')),
                                       menuItem('Marker Comparisons', 
                                                tabName = 'comparisons'),
                                       menuItem('Intensity Comparison',
                                                tabName = 'intensities'),
                                       menuItem('Tissue Representation',
                                                tabName = 'cell_map'),
                                       menuItem('Data Tables',
                                                tabName = 'datatable'),
                                       menuItem('About',
                                                tabName = 'about')
                                     )
                    ),
                    dashboardBody(
                      tabItems(
                        tabItem(tabName = 'comparisons',
                                fluidRow(column(12,
                                                p(strong("Parse the selected data under the Data tab"),  " and then select target markers to compare
                                                  against each other.",
                                                  style = 'text-align:justify;coor:black;background-color:white;padding:15px;border-radius:5px'),
                                                br())),
                                fluidRow(column(3, 
                                                selectInput('barChart_input',
                                                            'markers',
                                                            choices = 'none',
                                                            multiple = T,
                                                            selectize = T)),
                                         column(3,
                                                actionButton('comp_reset',
                                                             'Update'))),
                                tabBox(width = 12,
                                       title = 'Proportions',
                                       id = 'bar_pie',
                                       tabPanel('Bar Chart',
                                                fluidRow(column(3,
                                                                radioButtons('subset_bar',
                                                                             'Bar Chart',
                                                                             choices = c('% of subset',
                                                                                         '% of whole'))),
                                                         column(9,
                                                                plotOutput('barChart')))),
                                       tabPanel('Pie Chart',
                                                fluidRow(column(3,
                                                                radioButtons('subset_pie',
                                                                             'Donut Chart',
                                                                             choices = c('% of subset',
                                                                                         '% of whole'))),
                                                         column(9,
                                                                plotlyOutput('doughnutChart')))))),
                        tabItem(tabName = 'datatable',
                                fluidRow(column(12,
                                                p(strong("Parse the selected data under the Data tab."),  " The resulting datatables are parsed from the file and 
                                                  are downloadable as CSVs."),
                                                style = 'text-align:justify;coor:black;background-color:white;padding:15px;border-radius:5px')),
                                br(),
                                tabBox(width = 12,
                                       title = "Dataset",
                                       id = 'dataset',
                                       tabPanel("Classifications",
                                                div(style = 'overflow-y:scroll;height:600px;',
                                                    dataTableOutput('classification_dataset'),
                                                    downloadButton('download_classification_cols', 'Download'))),
                                       tabPanel('Intensities',
                                                div(style = 'overflow-y:scroll;height:600px;',
                                                    dataTableOutput('intensity_dataset'),
                                                    downloadButton('download_intensity_cols', 'Download'))),
                                       tabPanel('Double Positives',
                                                div(style = 'overflow-y:scroll;height:625px;',
                                                    dataTableOutput('double_positive_data'),
                                                    downloadButton('download_dp_total', 'Download'),
                                                    br(),
                                                    br(),
                                                    dataTableOutput('double_positive_percentages'),
                                                    downloadButton('download_dp_perc', 'Download'))),
                                       tabPanel('Full Dataset',
                                                div(style = 'overflow-y:scroll;height:600px;',
                                                    dataTableOutput('full_dataset'))))),
                        tabItem(tabName = 'intensities',
                                fluidRow(column(12,
                                                p(strong("Parse the selected data under the Data tab"),  " and then select individual markers for the 
                                                x and y axes to plot intensity values against each other. Make sure to choose", strong("two different markers"),
                                                  style = 'text-align:justify;coor:black;background-color:white;padding:15px;border-radius:5px'),
                                                br())),
                                fluidRow(column(2,
                                                actionButton('intensity_reset',
                                                             'Update'))),
                                fluidRow(column(2,
                                                selectInput('y_input',
                                                            'y-axis',
                                                            choices = NULL,
                                                            multiple = F,
                                                            selectize = T)),
                                         column(10,
                                                plotlyOutput('intensityChart'))),
                                fluidRow(column(2),
                                         column(10,
                                                selectInput('x_input',
                                                            'x-axis',
                                                            choices = NULL,
                                                            multiple = F,
                                                            selectize = T))),
                                fluidRow(column(3,
                                                radioButtons('intensity_choices',
                                                             'Intensity Values',
                                                             choices = c('all',
                                                                         'positive',
                                                                         'double positive',
                                                                         'positive (no double positive)',
                                                                         'negative'))),
                                         column(3,
                                                radioButtons('log_trans',
                                                             'Log Transformation',
                                                             choices = c('yes', 
                                                                         'no'))))),
                        tabItem(tabName = 'cell_map',
                                tabBox(width = 12,
                                       tabPanel('Two Markers',
                                                div(style = 'overflow-y:scroll;height:700px;',
                                                    fluidRow(column(12,
                                                                    p(strong("Parse the selected data under the Data tab"),  " and then select individual markers for the 
                                                Marker 1 and Marker 2. The resulting graph is a representation of the tissue mapping locations of what cells are positive for 
                                                                      selected markers and where they are double-positive"),
                                                                    style = 'text-align:justify;coor:black;background-color:white;padding:15px;border-radius:5px'),
                                                             br()),
                                                    fluidRow(column(3,
                                                                    actionButton('map_update',
                                                                                 'Update')),
                                                             column(3,
                                                                    selectInput('marker_1',
                                                                                'Marker 1',
                                                                                choices = NULL,
                                                                                multiple = F,
                                                                                selectize = T)),
                                                             column(3,
                                                                    selectInput('marker_2',
                                                                                'Marker 2',
                                                                                choices = NULL,
                                                                                multiple = F,
                                                                                selectize = T))),
                                                    tags$style(type = "text/css", "#cellMap {height: calc(100vh - 10px) !important;}"),
                                                    fillPage(plotlyOutput("cellMap", height="100%", width="100%")))),
                                       tabPanel('Individual Marker',
                                                div(style = 'overflow-y:scroll;height:700px;',
                                                    fluidRow(column(12,
                                                                    p(strong("Parse the selected data under the Data tab"),  " and then select markers. The resulting graph is a 
                                                                    representation of the tissue mapping locations of what cells are positive for the 
                                                                      selected marker"),
                                                                    style = 'text-align:justify;coor:black;background-color:white;padding:15px;border-radius:5px'),
                                                             br()),
                                                    fluidRow(column(3,
                                                                    actionButton('ind_map_update',
                                                                                 'Update')),
                                                             column(3,
                                                                    selectInput('marker_ind',
                                                                                'Marker',
                                                                                choices = NULL,
                                                                                multiple = F,
                                                                                selectize = T))),
                                                    tags$style(type = "text/css", "#cellMap_ind {height: calc(100vh - 10px) !important;}"),
                                                    fillPage(plotlyOutput("cellMap_ind", height="100%", width="100%")))
                                                
                                       )
                                )
                        )
                      )
                    )
                  )
))