library(shinydashboard)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
    dashboardPage(
        dashboardHeader(title = 'HALO Object Analysis'),
        
        dashboardSidebar(width = 300,
                         sidebarMenu(
                             menuItem('Data', 
                                      tabName = 'file_input',
                                      fileInput('file',
                                                label = h3('File input'),
                                                multiple = F,
                                                accept = c(".tsv",
                                                           ".csv"))),
                             menuItem('Marker Comparisons', 
                                      tabName = 'comparisons'),
                             menuItem('Intensity Comparison',
                                      tabName = 'intensities'),
                             menuItem('Tissue Representation',
                                      tabName = 'cell_map'),
                             menuItem('Data Tables',
                                      tabName = 'datatable')
                         )
        ),
        dashboardBody(
            tabItems(
                tabItem(tabName = 'comparisons',
                        fluidRow(column(3, 
                                        selectInput('barChart_input',
                                                    'markers',
                                                    choices = 'none',
                                                    multiple = T,
                                                    selectize = T)),
                                 column(3,
                                        actionButton('comp_reset',
                                                     'Update'))),
                        tabBox(width = 12,
                               title = 'Proportions',
                               id = 'bar_pie',
                               tabPanel('Pie Chart',
                                        fluidRow(column(3,
                                                        radioButtons('subset_pie',
                                                                     'Pie Chart',
                                                                     choices = c('% of subset',
                                                                                 '% of whole'))),
                                                 column(9,
                                                        plotlyOutput('doughnutChart')))),
                               tabPanel('Bar Chart',
                                        fluidRow(column(3,
                                                        radioButtons('subset_bar',
                                                                     'Bar Chart',
                                                                     choices = c('% of subset',
                                                                                 '% of whole'))),
                                                 column(9,
                                                        plotOutput('barChart')))))),
                tabItem(tabName = 'datatable',
                        tabBox(width = 12,
                               title = "Dataset",
                               id = 'dataset',
                               tabPanel("Classifications",
                                        dataTableOutput('classification_dataset'),
                                        downloadButton('download_classification_cols', 'Download')),
                               tabPanel('Intensities',
                                        dataTableOutput('intensity_dataset'),
                                        downloadButton('download_intensity_cols', 'Download')),
                               tabPanel('Double Positives',
                                        dataTableOutput('double_positive_data'),
                                        downloadButton('download_dp_total', 'Download'),
                                        dataTableOutput('double_positive_percentages'),
                                        downloadButton('download_dp_perc', 'Download')),
                               tabPanel('Full Dataset',
                                        dataTableOutput('full_dataset')))),
                tabItem(tabName = 'intensities',
                        fluidRow(column(2,
                                        actionButton('intensity_reset',
                                                     'Update'))),
                        fluidRow(column(2,
                                        selectInput('y_input',
                                                    'y-axis',
                                                    choices = 'none',
                                                    multiple = F,
                                                    selectize = T)),
                                 column(10,
                                        plotlyOutput('intensityChart'))),
                        fluidRow(column(2),
                                 column(10,
                                        selectInput('x_input',
                                                    'x-axis',
                                                    choices = 'none',
                                                    multiple = F,
                                                    selectize = T))),
                        fluidRow(column(3,
                                        radioButtons('intensity_choices',
                                                     'Intensity Values',
                                                     choices = c('all',
                                                                 'positive',
                                                                 'double positive',
                                                                 'positive (no double positive)',
                                                                 'negative'))),
                                 column(3,
                                        radioButtons('log_trans',
                                                     'Log Transformation',
                                                     choices = c('yes', 
                                                                 'no'))))),
                tabItem(tabName = 'cell_map',
                        fluidRow(column(3,
                                        actionButton('map_update',
                                                     'Update')),
                                 column(3,
                                        selectInput('marker_1',
                                                    'Marker 1',
                                                    choices = 'none',
                                                    multiple = F,
                                                    selectize = T)),
                                 column(3,
                                        selectInput('marker_2',
                                                    'Marker 2',
                                                    choices = 'none',
                                                    multiple = F,
                                                    selectize = T))),
                        tags$style(type = "text/css", "#cellMap {height: calc(100vh - 10px) !important;}"),
                        fillPage(plotlyOutput("cellMap", height="100%", width="100%"))
                )
            )
        )
    )
))